/*
* generated by Xtext
*/
package org.ioicompanies.lang.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class IOIOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
