
package net.webservicex;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "country", targetNamespace = "http://www.webserviceX.NET", wsdlLocation = "http://www.webservicex.net/country.asmx?WSDL")
public class Country
    extends Service
{

    private final static URL COUNTRY_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://www.webservicex.net/country.asmx?WSDL");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        COUNTRY_WSDL_LOCATION = url;
    }

    public Country(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Country() {
        super(COUNTRY_WSDL_LOCATION, new QName("http://www.webserviceX.NET", "country"));
    }

    /**
     * 
     * @return
     *     returns CountrySoap
     */
    @WebEndpoint(name = "countrySoap")
    public CountrySoap getCountrySoap() {
        return (CountrySoap)super.getPort(new QName("http://www.webserviceX.NET", "countrySoap"), CountrySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountrySoap
     */
    @WebEndpoint(name = "countrySoap")
    public CountrySoap getCountrySoap(WebServiceFeature... features) {
        return (CountrySoap)super.getPort(new QName("http://www.webserviceX.NET", "countrySoap"), CountrySoap.class, features);
    }

}
