package company.hibernate.mapping;
// Generated 26.10.2011 15:04:34 by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="employee",
    catalog="101companies",
    uniqueConstraints = @UniqueConstraint(columnNames={"name", "address"}) 
)
public class Employee implements Serializable {


    private Long id;
    private Company company;
    private Department department;
    private String name;
    private String address;
    private double salary;
    private boolean manager;

    public Employee() {}

    public Employee(Company company, Department department, String name, String address, double salary, boolean manager) {
       this.company = company;
       this.department = department;
       this.name = name;
       this.address = address;
       this.salary = salary;
       this.manager = manager;
    }
   
    @Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cid", nullable=false)
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="did", nullable=false)
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="address", nullable=false, length=50)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="salary", nullable=false, precision=22, scale=0)
    public double getSalary() {
        return this.salary;
    }
    
    public void setSalary(double salary) {
        this.salary = salary;
    }
    
    @Column(name="manager", nullable=false)
    public boolean isManager() {
        return this.manager;
    }
    
    public void setManager(boolean manager) {
        this.manager = manager;
    }




}


