package company.rdb.mapping;
// Generated 06.10.2011 18:06:22 by Hibernate Tools 3.2.1.GA

import company.dao.exception.CompanyException;
import company.dao.factory.DAOFactory;
import company.dao.factory.FactoryManager;
import company.dao.interfaces.DepartmentDAO;
import company.dao.interfaces.EmployeeDAO;
import company.dao.interfaces.entities.CompanyInterface;
import company.dao.interfaces.entities.DepartmentInterface;
import company.dao.interfaces.entities.EmployeeInterface;
import company.dao.rdb.RdbDepartmentDAO;
import company.dao.rdb.RdbEmployeeDAO;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable, CompanyInterface {

    private Integer id;
    private String name;

    public Company() {
    
    }
	
    public Company(String name) {
        this.name = name;
    }
   
    @Override
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Override
    public String getName() {
        return this.name;
    }
    
    @Override
    public void setName(String name) {
        this.name = name;
    }
    
    @Override
    public Set<DepartmentInterface> getDepartments() throws CompanyException {
        try {
            DAOFactory factory = FactoryManager.getInstance().getDaoFactory();
            DepartmentDAO dao = factory.getDepartmentDAO();
            List<DepartmentInterface> departments;
            departments = ((RdbDepartmentDAO)dao).loadDepartmentsForCompany(this.id);
            
            return new HashSet<DepartmentInterface>(departments);
        } catch (CompanyException ex) {
            throw new CompanyException(ex.getMessage());
        }
    }

    @Override
    public double total() throws CompanyException {
        try {
            DAOFactory daoFactory = FactoryManager.getInstance().getDaoFactory();
            EmployeeDAO dao = daoFactory.getEmployeeDAO();
            List<EmployeeInterface> employees = ((RdbEmployeeDAO)dao).loadEmployeesForCompany(this.id);
            
            double total = 0d;
            for (EmployeeInterface employee : employees) {
                total += employee.getSalary();
            }
            
            return total;
        } catch (CompanyException ex) {
            throw new CompanyException(ex.getMessage());
        }
    }

    @Override
    public void cut() throws CompanyException {
        try {
            DAOFactory daoFactory = FactoryManager.getInstance().getDaoFactory();
            EmployeeDAO dao = daoFactory.getEmployeeDAO();
            List<EmployeeInterface> employees = ((RdbEmployeeDAO)dao).loadEmployeesForCompany(this.id);
            
            for (EmployeeInterface employee : employees) {
                employee.setSalary(employee.getSalary() / 2);
                dao.update(employee);
            }
            
        } catch (CompanyException ex) {
            throw new CompanyException(ex.getMessage());
        }
    }
    
}


