//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.softlang.org/company.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.softlang.org/company.xsd", IsNullable=false)]
public partial class Company {
    
    private string nameField;
    
    private Department[] departmentField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Department")]
    public Department[] Department {
        get {
            return this.departmentField;
        }
        set {
            this.departmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.softlang.org/company.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.softlang.org/company.xsd", IsNullable=false)]
public partial class Department {
    
    private string nameField;
    
    private Employee managerField;
    
    private Department[] department1Field;
    
    private Employee[] employeeField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public Employee Manager {
        get {
            return this.managerField;
        }
        set {
            this.managerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Department")]
    public Department[] Department1 {
        get {
            return this.department1Field;
        }
        set {
            this.department1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Employee")]
    public Employee[] Employee {
        get {
            return this.employeeField;
        }
        set {
            this.employeeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.softlang.org/company.xsd")]
public partial class Employee {
    
    private string nameField;
    
    private string addressField;
    
    private double salaryField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public double Salary {
        get {
            return this.salaryField;
        }
        set {
            this.salaryField = value;
        }
    }
}
