//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.softlang.org/company.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.softlang.org/company.xsd", IsNullable=false)]
public partial class Company {
    
    private string nameField;
    
    private Department[] topLevelDepartmentField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TopLevelDepartment")]
    public Department[] TopLevelDepartment {
        get {
            return this.topLevelDepartmentField;
        }
        set {
            this.topLevelDepartmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.softlang.org/company.xsd")]
public partial class Department {
    
    private string nameField;
    
    private Employee managerField;
    
    private Department[] subDepartmentField;
    
    private Employee[] employeeField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public Employee Manager {
        get {
            return this.managerField;
        }
        set {
            this.managerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SubDepartment")]
    public Department[] SubDepartment {
        get {
            return this.subDepartmentField;
        }
        set {
            this.subDepartmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Employee")]
    public Employee[] Employee {
        get {
            return this.employeeField;
        }
        set {
            this.employeeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.softlang.org/company.xsd")]
public partial class Employee {
    
    private string nameField;
    
    private string addressField;
    
    private double salaryField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public double Salary {
        get {
            return this.salaryField;
        }
        set {
            this.salaryField = value;
        }
    }
}
