/*
* generated by Xtext
*/
package org.ioicompanies.lang;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class IOIUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.ioicompanies.lang.ui.internal.IOIActivator.getInstance().getInjector("org.ioicompanies.lang.IOI");
	}
	
}
