package company.mapping;
// Generated 06.10.2011 18:06:22 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company  implements java.io.Serializable {


    private Integer id;
    private String name;
    private Set<Department> departments = new HashSet<Department>(0);
    private Set<Employee> employees = new HashSet<Employee>(0);

    public Company() {
    }

	
    public Company(String name) {
        this.name = name;
    }
    public Company(String name, Set<Department> departments, Set<Employee> employees) {
       this.name = name;
       this.departments = departments;
       this.employees = employees;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Department> getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set<Department> departments) {
        this.departments = departments;
    }
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }
    
    // --------------------------------------------------------
    
    public double total() {
        double total = 0d;
        for (Employee employee : employees) {
            total += employee.getSalary();
        }
        return total;
    }
    
}


