package company.mapping;
// Generated 06.10.2011 18:06:22 by Hibernate Tools 3.2.1.GA



/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer id;
     private Company company;
     private Department department;
     private String name;
     private String address;
     private double salary;
     private boolean manager;

    public Employee() {
    }

    public Employee(Company company, Department department, String name, String address, double salary, boolean manager) {
       this.company = company;
       this.department = department;
       this.name = name;
       this.address = address;
       this.salary = salary;
       this.manager = manager;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public double getSalary() {
        return this.salary;
    }
    
    public void setSalary(double salary) {
        this.salary = salary;
    }
    public boolean isManager() {
        return this.manager;
    }
    
    public void setManager(boolean manager) {
        this.manager = manager;
    }

    // --------------------------------------------------------
    public void cut() {
        salary /= 2;
    }


}


