-- SQL statements which are executed at application startup if hibernate.hbm2ddl.auto is 'create' or 'create-drop'



INSERT INTO TB_101_COMPANY(ID, NAME) VALUES (1, 'Meganalysis');

-- we do not set a manager as being an employee of 
-- a department.
-- I think that we could have modeled this better.

INSERT INTO TB_101_EMPLOYEE(ID, NAME, ADDRESS, SALARY) VALUES(1, 'Craig', 'Redmond', 123456);
INSERT INTO TB_101_EMPLOYEE(ID, NAME, ADDRESS, SALARY) VALUES(2, 'Ray', 'Redmond', 234567);
INSERT INTO TB_101_EMPLOYEE(ID, NAME, ADDRESS, SALARY) VALUES(3, 'Klaus', 'Boston', 23456);
INSERT INTO TB_101_EMPLOYEE(ID, NAME, ADDRESS, SALARY) VALUES(4, 'Karl', 'Riga', 2345);



INSERT INTO TB_101_DEPARTMENT(ID, NAME, MANAGER_ID, COMPANY_ID) VALUES(1,'Research', 1, 1);
INSERT INTO TB_101_DEPARTMENT(ID, NAME, MANAGER_ID, COMPANY_ID) VALUES(2,'Development', 2, 1);
INSERT INTO TB_101_DEPARTMENT(ID, NAME, MANAGER_ID, PARENT_ID)  VALUES(3,'Development-1', 3, 2);
INSERT INTO TB_101_DEPARTMENT(ID, NAME, MANAGER_ID, PARENT_ID)  VALUES(4,'Development-1.1', 4, 3);

 
INSERT INTO TB_101_EMPLOYEE(ID, NAME, ADDRESS, SALARY, DEPARTMENT_ID) VALUES(5, 'Erik', 'Utrecht', 12345, 1);
INSERT INTO TB_101_EMPLOYEE(ID, NAME, ADDRESS, SALARY, DEPARTMENT_ID) VALUES(6, 'Ralf', 'Koblenz', 1234, 1);

INSERT INTO TB_101_EMPLOYEE(ID, NAME, ADDRESS, SALARY, DEPARTMENT_ID) VALUES(7, 'Joe', 'Wifi City', 2344, 4);




 
 
