all:
	make Reverse
	make Sorting
	make Stack
	make Monoids
	make Evaluation

Reverse:
	@echo main | ghci Reverse.hs

Sorting:
	@echo main | ghci Sorting.hs

Stack:
	@echo main | ghci -i../../concepts/Stack Stack.hs

Monoids:
	@echo main | ghci Monoids.hs

Evaluation:
	@echo main | ghci Evaluation.hs
