all:
	make Reverse
	make Sorting
	make Classification
	make Stack
	make Monoids
	make Evaluation
	make GenDemo

Reverse:
	@echo main | ghci Reverse.hs

Sorting:
	@echo main | ghci Sorting.hs

Classification:
	@echo main | ghci Classification.hs

Stack:
	@echo main | ghci -i../../concepts/Stack Stack.hs

Monoids:
	@echo main | ghci Monoids.hs

Evaluation:
	@echo main | ghci Evaluation.hs

GenDemo:
	@echo main | ghci GenDemo.hs
