/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package company.validation;

import company.Employee;
import company.Subunit;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link company.Dept}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DeptValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateManager(Employee value);
	boolean validateSubunits(EList<Subunit> value);
}
