/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package company.validation;

import company.Dept;
import company.Employee;

/**
 * A sample validator interface for {@link company.Subunit}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SubunitValidator {
	boolean validate();

	boolean validatePu(Employee value);
	boolean validateDu(Dept value);
}
