/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.oneoonecompanies.schema;

import de.uni_koblenz.jgralab.EdgeDirection;

public interface Company extends de.uni_koblenz.oneoonecompanies.schema.NamedElement {

	/**
	 * @return the next de.uni_koblenz.oneoonecompanies.schema.Company vertex in the global vertex sequence
	 */
	public de.uni_koblenz.oneoonecompanies.schema.Company getNextCompany();

	/**
	 * @return the next de.uni_koblenz.oneoonecompanies.schema.NamedElement vertex in the global vertex sequence
	 */
	public de.uni_koblenz.oneoonecompanies.schema.NamedElement getNextNamedElement();

	/**
	 * @return the first edge of class HasDepartment at this vertex
	 */
	public de.uni_koblenz.oneoonecompanies.schema.HasDepartment getFirstHasDepartmentIncidence();

	/**
	 * @return the first edge of class HasDepartment at this vertex
	 * @param orientation the orientation of the edge
	 */
	public de.uni_koblenz.oneoonecompanies.schema.HasDepartment getFirstHasDepartmentIncidence(EdgeDirection orientation);
		/**
		 * adds the given vertex as <code>departments</code> to this vertex, i.e. creates an
		 * <code>de.uni_koblenz.oneoonecompanies.schema.HasDepartment</code> edge from this vertex to the given 
		 * one and returns the created edge.
		 * @return  a newly created edge of type <code>de.uni_koblenz.oneoonecompanies.schema.HasDepartment</code>
		 *          between this vertex and the given one.
		 */
		public de.uni_koblenz.oneoonecompanies.schema.HasDepartment add_departments(de.uni_koblenz.oneoonecompanies.schema.Department vertex);
		/**
		 * removes all departments adjacences to all vertices by 
		 * deleting the <code>de.uni_koblenz.oneoonecompanies.schema.HasDepartment</code> edges of this vertex to 
		 * all other ones, but doesn't delete those vertices.
		 *
		 * @return the adjacent vertices prior to removal of incidences
		 */
		public java.util.List<? extends de.uni_koblenz.oneoonecompanies.schema.Department> remove_departments();
		/**
		 * removes the given vertex as <code>departments</code> from this vertex, i.e. 
		 * deletes the <code>de.uni_koblenz.oneoonecompanies.schema.HasDepartment</code> edge connections of this vertex with 
		 * the given one.
		 */
		public boolean remove_departments(de.uni_koblenz.oneoonecompanies.schema.Department vertex);
		/**
		 * @return an Iterable of all vertices adjacent to this one with the rolename 'departments'
		 *         (connected with a <code>de.uni_koblenz.oneoonecompanies.schema.HasDepartment</code> edge).
		 */
		public Iterable<? extends de.uni_koblenz.oneoonecompanies.schema.Department> get_departments();

	/**
	 * Returns an Iterable for all incidence edges of this vertex that are of type HasDepartment or subtypes.
	 */
	public Iterable<de.uni_koblenz.oneoonecompanies.schema.HasDepartment> getHasDepartmentIncidences();
	
	
	/**
	 * Returns an Iterable for all incidence edges of this vertex that are of type HasDepartment.
	 * @param direction EdgeDirection.IN or EdgeDirection.OUT, only edges of this direction will be included in the Iterable
	 */
	public Iterable<de.uni_koblenz.oneoonecompanies.schema.HasDepartment> getHasDepartmentIncidences(EdgeDirection direction);
}
