#
# Make java-prefix empty if javac/xjc of Java 6 is in your path
# The sample here is Mac OS 10.5+-specific.
#

java-prefix = /System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Commands/

generate:
	${java-prefix}xjc Company.xsd
