/*
 * generated by Xtext
 */
package org.ioicompanies.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class IOIUiModule extends org.ioicompanies.lang.ui.AbstractIOIUiModule {
	public IOIUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
