/*
 * generated by Xtext
 */
package org.ioicompanies.lang;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IOIRuntimeModule extends org.ioicompanies.lang.AbstractIOIRuntimeModule {

}
