
package de.unikoblenz.sle;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WordingService", targetNamespace = "http://sle.unikoblenz.de/", wsdlLocation = "http://localhost:8080/B-A-Local-WS/Wording?wsdl")
public class WordingService
    extends Service
{

    private final static URL WORDINGSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/B-A-Local-WS/Wording?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WORDINGSERVICE_WSDL_LOCATION = url;
    }

    public WordingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WordingService() {
        super(WORDINGSERVICE_WSDL_LOCATION, new QName("http://sle.unikoblenz.de/", "WordingService"));
    }

    /**
     * 
     * @return
     *     returns Wording
     */
    @WebEndpoint(name = "WordingPort")
    public Wording getWordingPort() {
        return (Wording)super.getPort(new QName("http://sle.unikoblenz.de/", "WordingPort"), Wording.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Wording
     */
    @WebEndpoint(name = "WordingPort")
    public Wording getWordingPort(WebServiceFeature... features) {
        return (Wording)super.getPort(new QName("http://sle.unikoblenz.de/", "WordingPort"), Wording.class, features);
    }

}
