/*
 * generated by Xtext
 */
package org.ioicompanies.lang.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.ioicompanies.lang.ui.internal.IOIActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IOIExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return IOIActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return IOIActivator.getInstance().getInjector(IOIActivator.ORG_IOICOMPANIES_LANG_IOI);
	}
	
}
