/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.oneoonecompanies.schema.impl.std;

import de.uni_koblenz.jgralab.impl.EdgeIterable;
import de.uni_koblenz.jgralab.impl.VertexIterable;

import de.uni_koblenz.jgralab.impl.std.GraphImpl;

import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;
import de.uni_koblenz.jgralab.NoSuchAttributeException;

import de.uni_koblenz.oneoonecompanies.schema.OneOOneSchema;

import de.uni_koblenz.jgralab.Vertex;
import de.uni_koblenz.jgralab.greql2.evaluator.GreqlEvaluator;
import de.uni_koblenz.jgralab.greql2.jvalue.JValue;
import de.uni_koblenz.jgralab.greql2.jvalue.JValueImpl;
import de.uni_koblenz.jgralab.greql2.jvalue.JValueSet;

import java.io.IOException;
import java.util.List;

public class CompaniesGraphImpl extends GraphImpl implements de.uni_koblenz.oneoonecompanies.schema.CompaniesGraph, de.uni_koblenz.jgralab.Graph {

	/* Constructors and create methods with values for initial vertex and edge count */
	public CompaniesGraphImpl(int vMax, int eMax) {
		this(null, vMax, eMax);
	}
	
	public CompaniesGraphImpl(java.lang.String id, int vMax, int eMax) {
		super(id, OneOOneSchema.instance().gc_CompaniesGraph, vMax, eMax);
		initializeAttributesWithDefaultValues();
	}
	
	public static de.uni_koblenz.oneoonecompanies.schema.CompaniesGraph create(int vMax, int eMax) {
		return (de.uni_koblenz.oneoonecompanies.schema.CompaniesGraph) OneOOneSchema.instance().createCompaniesGraph(null, vMax, eMax);
	}
	
	public static de.uni_koblenz.oneoonecompanies.schema.CompaniesGraph create(String id, int vMax, int eMax) {
		return (de.uni_koblenz.oneoonecompanies.schema.CompaniesGraph) OneOOneSchema.instance().createCompaniesGraph(id, vMax, eMax);
	}
	
	/* Constructors and create methods without values for initial vertex and edge count */
	public CompaniesGraphImpl() {
		this(null);
	}
	
	public CompaniesGraphImpl(java.lang.String id) {
		super(id, OneOOneSchema.instance().gc_CompaniesGraph);
		initializeAttributesWithDefaultValues();
	}
	
	public static de.uni_koblenz.oneoonecompanies.schema.CompaniesGraph create() {
		return (de.uni_koblenz.oneoonecompanies.schema.CompaniesGraph) OneOOneSchema.instance().createCompaniesGraph(null);
	}
	
	public static de.uni_koblenz.oneoonecompanies.schema.CompaniesGraph create(String id) {
		return (de.uni_koblenz.oneoonecompanies.schema.CompaniesGraph) OneOOneSchema.instance().createCompaniesGraph(id);
	}

	public final de.uni_koblenz.jgralab.schema.AttributedElementClass getAttributedElementClass() {
		return de.uni_koblenz.oneoonecompanies.schema.OneOOneSchema.instance().gc_CompaniesGraph;
	}

	public final java.lang.Class<? extends de.uni_koblenz.jgralab.AttributedElement> getM1Class() {
		return de.uni_koblenz.oneoonecompanies.schema.CompaniesGraph.class;
	}

	public Object getAttribute(String attributeName) {
		throw new NoSuchAttributeException("CompaniesGraph doesn't contain an attribute " + attributeName);
	}

	public void setAttribute(String attributeName, Object data) {
		throw new NoSuchAttributeException("CompaniesGraph doesn't contain an attribute " + attributeName);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void readAttributeValueFromString(String attributeName, String value) throws GraphIOException {
		throw new NoSuchAttributeException("CompaniesGraph doesn't contain an attribute " + attributeName);
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public String writeAttributeValueToString(String attributeName) throws IOException, GraphIOException {
		throw new NoSuchAttributeException("CompaniesGraph doesn't contain an attribute " + attributeName);
	}
	
	protected GreqlEvaluator greqlEvaluator = null;

	@SuppressWarnings("unchecked") 
	@Override 
	public synchronized <T extends Vertex> List<T> reachableVertices(Vertex startVertex, String pathDescription, Class<T> vertexType) { 
		if (greqlEvaluator == null) { 
			greqlEvaluator = new GreqlEvaluator((String) null, this, null); 
		} 
		greqlEvaluator.setVariable("v", new JValueImpl(startVertex)); 
		greqlEvaluator.setQuery("using v: v " + pathDescription); 
		greqlEvaluator.startEvaluation(); 
		JValueSet rs = greqlEvaluator.getEvaluationResult().toJValueSet(); 
		java.util.List<T> lst = new java.util.LinkedList<T>(); 
		for (JValue jv : rs) { 
			Vertex v = jv.toVertex();
			if (vertexType.isInstance(v)) {
				lst.add((T) v);
			}
		}
		return lst; 
	}

	// ------------------------ Code for Company ------------------------

	public de.uni_koblenz.oneoonecompanies.schema.Company getFirstCompany() {
		return (de.uni_koblenz.oneoonecompanies.schema.Company)getFirstVertex(OneOOneSchema.instance().vc_Company);
	}

	public de.uni_koblenz.oneoonecompanies.schema.Company createCompany() {
		de.uni_koblenz.oneoonecompanies.schema.Company newVertex = (de.uni_koblenz.oneoonecompanies.schema.Company) graphFactory.createVertex(de.uni_koblenz.oneoonecompanies.schema.Company.class, 0, this);
		return newVertex;
	}

	public de.uni_koblenz.oneoonecompanies.schema.Company createCompany(int id) {
		de.uni_koblenz.oneoonecompanies.schema.Company newVertex = (de.uni_koblenz.oneoonecompanies.schema.Company) graphFactory.createVertex(de.uni_koblenz.oneoonecompanies.schema.Company.class, id, this);
		return newVertex;
	}

	// ------------------------ Code for Department ------------------------

	public de.uni_koblenz.oneoonecompanies.schema.Department getFirstDepartment() {
		return (de.uni_koblenz.oneoonecompanies.schema.Department)getFirstVertex(OneOOneSchema.instance().vc_Department);
	}

	public de.uni_koblenz.oneoonecompanies.schema.Department createDepartment() {
		de.uni_koblenz.oneoonecompanies.schema.Department newVertex = (de.uni_koblenz.oneoonecompanies.schema.Department) graphFactory.createVertex(de.uni_koblenz.oneoonecompanies.schema.Department.class, 0, this);
		return newVertex;
	}

	public de.uni_koblenz.oneoonecompanies.schema.Department createDepartment(int id) {
		de.uni_koblenz.oneoonecompanies.schema.Department newVertex = (de.uni_koblenz.oneoonecompanies.schema.Department) graphFactory.createVertex(de.uni_koblenz.oneoonecompanies.schema.Department.class, id, this);
		return newVertex;
	}

	// ------------------------ Code for Employee ------------------------

	public de.uni_koblenz.oneoonecompanies.schema.Employee getFirstEmployee() {
		return (de.uni_koblenz.oneoonecompanies.schema.Employee)getFirstVertex(OneOOneSchema.instance().vc_Employee);
	}

	public de.uni_koblenz.oneoonecompanies.schema.Employee createEmployee() {
		de.uni_koblenz.oneoonecompanies.schema.Employee newVertex = (de.uni_koblenz.oneoonecompanies.schema.Employee) graphFactory.createVertex(de.uni_koblenz.oneoonecompanies.schema.Employee.class, 0, this);
		return newVertex;
	}

	public de.uni_koblenz.oneoonecompanies.schema.Employee createEmployee(int id) {
		de.uni_koblenz.oneoonecompanies.schema.Employee newVertex = (de.uni_koblenz.oneoonecompanies.schema.Employee) graphFactory.createVertex(de.uni_koblenz.oneoonecompanies.schema.Employee.class, id, this);
		return newVertex;
	}

	// ------------------------ Code for HasDepartment ------------------------

	public de.uni_koblenz.oneoonecompanies.schema.HasDepartment getFirstHasDepartment() {
		return (de.uni_koblenz.oneoonecompanies.schema.HasDepartment)getFirstEdge(OneOOneSchema.instance().ec_HasDepartment);
	}

	public de.uni_koblenz.oneoonecompanies.schema.HasDepartment createHasDepartment(de.uni_koblenz.oneoonecompanies.schema.Company alpha, de.uni_koblenz.oneoonecompanies.schema.Department omega) {
		de.uni_koblenz.oneoonecompanies.schema.HasDepartment newEdge = (de.uni_koblenz.oneoonecompanies.schema.HasDepartment) graphFactory.createEdge(de.uni_koblenz.oneoonecompanies.schema.HasDepartment.class, 0, this, alpha, omega);
		return newEdge;
	}

	public de.uni_koblenz.oneoonecompanies.schema.HasDepartment createHasDepartment(int id, de.uni_koblenz.oneoonecompanies.schema.Company alpha, de.uni_koblenz.oneoonecompanies.schema.Department omega) {
		de.uni_koblenz.oneoonecompanies.schema.HasDepartment newEdge = (de.uni_koblenz.oneoonecompanies.schema.HasDepartment) graphFactory.createEdge(de.uni_koblenz.oneoonecompanies.schema.HasDepartment.class, id, this, alpha, omega);
		return newEdge;
	}

	// ------------------------ Code for HasEmployee ------------------------

	public de.uni_koblenz.oneoonecompanies.schema.HasEmployee getFirstHasEmployee() {
		return (de.uni_koblenz.oneoonecompanies.schema.HasEmployee)getFirstEdge(OneOOneSchema.instance().ec_HasEmployee);
	}

	public de.uni_koblenz.oneoonecompanies.schema.HasEmployee createHasEmployee(de.uni_koblenz.oneoonecompanies.schema.Department alpha, de.uni_koblenz.oneoonecompanies.schema.Person omega) {
		de.uni_koblenz.oneoonecompanies.schema.HasEmployee newEdge = (de.uni_koblenz.oneoonecompanies.schema.HasEmployee) graphFactory.createEdge(de.uni_koblenz.oneoonecompanies.schema.HasEmployee.class, 0, this, alpha, omega);
		return newEdge;
	}

	public de.uni_koblenz.oneoonecompanies.schema.HasEmployee createHasEmployee(int id, de.uni_koblenz.oneoonecompanies.schema.Department alpha, de.uni_koblenz.oneoonecompanies.schema.Person omega) {
		de.uni_koblenz.oneoonecompanies.schema.HasEmployee newEdge = (de.uni_koblenz.oneoonecompanies.schema.HasEmployee) graphFactory.createEdge(de.uni_koblenz.oneoonecompanies.schema.HasEmployee.class, id, this, alpha, omega);
		return newEdge;
	}

	// ------------------------ Code for HasSubDepartment ------------------------

	public de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment getFirstHasSubDepartment() {
		return (de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment)getFirstEdge(OneOOneSchema.instance().ec_HasSubDepartment);
	}

	public de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment createHasSubDepartment(de.uni_koblenz.oneoonecompanies.schema.Department alpha, de.uni_koblenz.oneoonecompanies.schema.Department omega) {
		de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment newEdge = (de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment) graphFactory.createEdge(de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment.class, 0, this, alpha, omega);
		return newEdge;
	}

	public de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment createHasSubDepartment(int id, de.uni_koblenz.oneoonecompanies.schema.Department alpha, de.uni_koblenz.oneoonecompanies.schema.Department omega) {
		de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment newEdge = (de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment) graphFactory.createEdge(de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment.class, id, this, alpha, omega);
		return newEdge;
	}

	// ------------------------ Code for Manager ------------------------

	public de.uni_koblenz.oneoonecompanies.schema.Manager getFirstManager() {
		return (de.uni_koblenz.oneoonecompanies.schema.Manager)getFirstVertex(OneOOneSchema.instance().vc_Manager);
	}

	public de.uni_koblenz.oneoonecompanies.schema.Manager createManager() {
		de.uni_koblenz.oneoonecompanies.schema.Manager newVertex = (de.uni_koblenz.oneoonecompanies.schema.Manager) graphFactory.createVertex(de.uni_koblenz.oneoonecompanies.schema.Manager.class, 0, this);
		return newVertex;
	}

	public de.uni_koblenz.oneoonecompanies.schema.Manager createManager(int id) {
		de.uni_koblenz.oneoonecompanies.schema.Manager newVertex = (de.uni_koblenz.oneoonecompanies.schema.Manager) graphFactory.createVertex(de.uni_koblenz.oneoonecompanies.schema.Manager.class, id, this);
		return newVertex;
	}

	// ------------------------ Code for Mentors ------------------------

	public de.uni_koblenz.oneoonecompanies.schema.Mentors getFirstMentors() {
		return (de.uni_koblenz.oneoonecompanies.schema.Mentors)getFirstEdge(OneOOneSchema.instance().ec_Mentors);
	}

	public de.uni_koblenz.oneoonecompanies.schema.Mentors createMentors(de.uni_koblenz.oneoonecompanies.schema.Person alpha, de.uni_koblenz.oneoonecompanies.schema.Employee omega) {
		de.uni_koblenz.oneoonecompanies.schema.Mentors newEdge = (de.uni_koblenz.oneoonecompanies.schema.Mentors) graphFactory.createEdge(de.uni_koblenz.oneoonecompanies.schema.Mentors.class, 0, this, alpha, omega);
		return newEdge;
	}

	public de.uni_koblenz.oneoonecompanies.schema.Mentors createMentors(int id, de.uni_koblenz.oneoonecompanies.schema.Person alpha, de.uni_koblenz.oneoonecompanies.schema.Employee omega) {
		de.uni_koblenz.oneoonecompanies.schema.Mentors newEdge = (de.uni_koblenz.oneoonecompanies.schema.Mentors) graphFactory.createEdge(de.uni_koblenz.oneoonecompanies.schema.Mentors.class, id, this, alpha, omega);
		return newEdge;
	}

	// ------------------------ Code for NamedElement ------------------------

	public de.uni_koblenz.oneoonecompanies.schema.NamedElement getFirstNamedElement() {
		return (de.uni_koblenz.oneoonecompanies.schema.NamedElement)getFirstVertex(OneOOneSchema.instance().vc_NamedElement);
	}

	// ------------------------ Code for Person ------------------------

	public de.uni_koblenz.oneoonecompanies.schema.Person getFirstPerson() {
		return (de.uni_koblenz.oneoonecompanies.schema.Person)getFirstVertex(OneOOneSchema.instance().vc_Person);
	}

	public Iterable<de.uni_koblenz.oneoonecompanies.schema.HasDepartment> getHasDepartmentEdges() {
		return new EdgeIterable<de.uni_koblenz.oneoonecompanies.schema.HasDepartment>(this, de.uni_koblenz.oneoonecompanies.schema.HasDepartment.class);
	}
	

	public Iterable<de.uni_koblenz.oneoonecompanies.schema.Mentors> getMentorsEdges() {
		return new EdgeIterable<de.uni_koblenz.oneoonecompanies.schema.Mentors>(this, de.uni_koblenz.oneoonecompanies.schema.Mentors.class);
	}
	

	public Iterable<de.uni_koblenz.oneoonecompanies.schema.HasEmployee> getHasEmployeeEdges() {
		return new EdgeIterable<de.uni_koblenz.oneoonecompanies.schema.HasEmployee>(this, de.uni_koblenz.oneoonecompanies.schema.HasEmployee.class);
	}
	

	public Iterable<de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment> getHasSubDepartmentEdges() {
		return new EdgeIterable<de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment>(this, de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment.class);
	}
	

	public Iterable<de.uni_koblenz.oneoonecompanies.schema.NamedElement> getNamedElementVertices() {
		return new VertexIterable<de.uni_koblenz.oneoonecompanies.schema.NamedElement>(this, de.uni_koblenz.oneoonecompanies.schema.NamedElement.class);
	}
	

	public Iterable<de.uni_koblenz.oneoonecompanies.schema.Company> getCompanyVertices() {
		return new VertexIterable<de.uni_koblenz.oneoonecompanies.schema.Company>(this, de.uni_koblenz.oneoonecompanies.schema.Company.class);
	}
	

	public Iterable<de.uni_koblenz.oneoonecompanies.schema.Person> getPersonVertices() {
		return new VertexIterable<de.uni_koblenz.oneoonecompanies.schema.Person>(this, de.uni_koblenz.oneoonecompanies.schema.Person.class);
	}
	

	public Iterable<de.uni_koblenz.oneoonecompanies.schema.Manager> getManagerVertices() {
		return new VertexIterable<de.uni_koblenz.oneoonecompanies.schema.Manager>(this, de.uni_koblenz.oneoonecompanies.schema.Manager.class);
	}
	

	public Iterable<de.uni_koblenz.oneoonecompanies.schema.Department> getDepartmentVertices() {
		return new VertexIterable<de.uni_koblenz.oneoonecompanies.schema.Department>(this, de.uni_koblenz.oneoonecompanies.schema.Department.class);
	}
	

	public Iterable<de.uni_koblenz.oneoonecompanies.schema.Employee> getEmployeeVertices() {
		return new VertexIterable<de.uni_koblenz.oneoonecompanies.schema.Employee>(this, de.uni_koblenz.oneoonecompanies.schema.Employee.class);
	}
	
}
