/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.oneoonecompanies.schema.impl.std;

import de.uni_koblenz.jgralab.impl.std.EdgeImpl;

import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;
import de.uni_koblenz.jgralab.NoSuchAttributeException;
import de.uni_koblenz.jgralab.Vertex;

import de.uni_koblenz.oneoonecompanies.schema.impl.std.ReversedHasEmployeeImpl;

import java.io.IOException;
/**
 * FromVertexClass: Department
 * FromRoleName : department
 * ToVertexClass: Person
 * ToRoleName : persons
 */

public class HasEmployeeImpl extends EdgeImpl implements de.uni_koblenz.jgralab.Edge, de.uni_koblenz.oneoonecompanies.schema.HasEmployee {

	public HasEmployeeImpl(int id, de.uni_koblenz.jgralab.Graph g, Vertex alpha, Vertex omega) {
		super(id, g, alpha, omega);
	}

	public final de.uni_koblenz.jgralab.schema.AttributedElementClass getAttributedElementClass() {
		return de.uni_koblenz.oneoonecompanies.schema.OneOOneSchema.instance().ec_HasEmployee;
	}

	public final java.lang.Class<? extends de.uni_koblenz.jgralab.AttributedElement> getM1Class() {
		return de.uni_koblenz.oneoonecompanies.schema.HasEmployee.class;
	}

	public Object getAttribute(String attributeName) {
		throw new NoSuchAttributeException("HasEmployee doesn't contain an attribute " + attributeName);
	}

	public void setAttribute(String attributeName, Object data) {
		throw new NoSuchAttributeException("HasEmployee doesn't contain an attribute " + attributeName);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void readAttributeValueFromString(String attributeName, String value) throws GraphIOException {
		throw new NoSuchAttributeException("HasEmployee doesn't contain an attribute " + attributeName);
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public String writeAttributeValueToString(String attributeName) throws IOException, GraphIOException {
		throw new NoSuchAttributeException("HasEmployee doesn't contain an attribute " + attributeName);
	}

	public de.uni_koblenz.oneoonecompanies.schema.HasEmployee getNextHasEmployeeInGraph() {
		return (de.uni_koblenz.oneoonecompanies.schema.HasEmployee)getNextEdge(de.uni_koblenz.oneoonecompanies.schema.HasEmployee.class);
	}

	public de.uni_koblenz.oneoonecompanies.schema.HasEmployee getNextHasEmployee() {
		return (de.uni_koblenz.oneoonecompanies.schema.HasEmployee)getNextIncidence(de.uni_koblenz.oneoonecompanies.schema.HasEmployee.class);
	}

	public de.uni_koblenz.oneoonecompanies.schema.HasEmployee getNextHasEmployee(EdgeDirection orientation) {
		return (de.uni_koblenz.oneoonecompanies.schema.HasEmployee)getNextIncidence(de.uni_koblenz.oneoonecompanies.schema.HasEmployee.class, orientation);
	}

	public de.uni_koblenz.jgralab.schema.AggregationKind getSemantics() {
		return de.uni_koblenz.jgralab.schema.AggregationKind.SHARED;
	}

	@Override
	public de.uni_koblenz.jgralab.schema.AggregationKind getAlphaSemantics() {
		return de.uni_koblenz.jgralab.schema.AggregationKind.NONE;
	}

	@Override
	public de.uni_koblenz.jgralab.schema.AggregationKind getOmegaSemantics() {
		return de.uni_koblenz.jgralab.schema.AggregationKind.SHARED;
	}

	protected de.uni_koblenz.jgralab.impl.ReversedEdgeBaseImpl createReversedEdge() {
		return new ReversedHasEmployeeImpl(this, graph);
	}
}
