/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.oneoonecompanies.schema.impl.std;

import de.uni_koblenz.jgralab.impl.std.EdgeImpl;

import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;
import de.uni_koblenz.jgralab.NoSuchAttributeException;
import de.uni_koblenz.jgralab.Vertex;

import de.uni_koblenz.oneoonecompanies.schema.impl.std.ReversedHasSubDepartmentImpl;

import java.io.IOException;
/**
 * FromVertexClass: Department
 * FromRoleName : parentDept
 * ToVertexClass: Department
 * ToRoleName : subDepts
 */

public class HasSubDepartmentImpl extends EdgeImpl implements de.uni_koblenz.jgralab.Edge, de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment {

	public HasSubDepartmentImpl(int id, de.uni_koblenz.jgralab.Graph g, Vertex alpha, Vertex omega) {
		super(id, g, alpha, omega);
	}

	public final de.uni_koblenz.jgralab.schema.AttributedElementClass getAttributedElementClass() {
		return de.uni_koblenz.oneoonecompanies.schema.OneOOneSchema.instance().ec_HasSubDepartment;
	}

	public final java.lang.Class<? extends de.uni_koblenz.jgralab.AttributedElement> getM1Class() {
		return de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment.class;
	}

	public Object getAttribute(String attributeName) {
		throw new NoSuchAttributeException("HasSubDepartment doesn't contain an attribute " + attributeName);
	}

	public void setAttribute(String attributeName, Object data) {
		throw new NoSuchAttributeException("HasSubDepartment doesn't contain an attribute " + attributeName);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void readAttributeValueFromString(String attributeName, String value) throws GraphIOException {
		throw new NoSuchAttributeException("HasSubDepartment doesn't contain an attribute " + attributeName);
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public String writeAttributeValueToString(String attributeName) throws IOException, GraphIOException {
		throw new NoSuchAttributeException("HasSubDepartment doesn't contain an attribute " + attributeName);
	}

	public de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment getNextHasSubDepartmentInGraph() {
		return (de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment)getNextEdge(de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment.class);
	}

	public de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment getNextHasSubDepartment() {
		return (de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment)getNextIncidence(de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment.class);
	}

	public de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment getNextHasSubDepartment(EdgeDirection orientation) {
		return (de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment)getNextIncidence(de.uni_koblenz.oneoonecompanies.schema.HasSubDepartment.class, orientation);
	}

	public de.uni_koblenz.jgralab.schema.AggregationKind getSemantics() {
		return de.uni_koblenz.jgralab.schema.AggregationKind.COMPOSITE;
	}

	@Override
	public de.uni_koblenz.jgralab.schema.AggregationKind getAlphaSemantics() {
		return de.uni_koblenz.jgralab.schema.AggregationKind.NONE;
	}

	@Override
	public de.uni_koblenz.jgralab.schema.AggregationKind getOmegaSemantics() {
		return de.uni_koblenz.jgralab.schema.AggregationKind.COMPOSITE;
	}

	protected de.uni_koblenz.jgralab.impl.ReversedEdgeBaseImpl createReversedEdge() {
		return new ReversedHasSubDepartmentImpl(this, graph);
	}
}
