/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.oneoonecompanies.schema.impl.std;

import de.uni_koblenz.jgralab.impl.IncidenceIterable;

import de.uni_koblenz.jgralab.impl.std.VertexImpl;

import de.uni_koblenz.jgralab.Edge;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;
import de.uni_koblenz.jgralab.NoSuchAttributeException;

import de.uni_koblenz.jgralab.schema.impl.DirectedM1EdgeClass;

import java.io.IOException;
import java.util.HashSet;
import java.util.Set;

public class ManagerImpl extends VertexImpl implements de.uni_koblenz.oneoonecompanies.schema.Manager, de.uni_koblenz.oneoonecompanies.schema.Person {

	protected java.lang.String _address;

	protected java.lang.String _name;

	protected int _salary;

	public ManagerImpl(int id, de.uni_koblenz.jgralab.Graph g) {
		super(id, g);
	}

	public final de.uni_koblenz.jgralab.schema.AttributedElementClass getAttributedElementClass() {
		return de.uni_koblenz.oneoonecompanies.schema.OneOOneSchema.instance().vc_Manager;
	}

	public final java.lang.Class<? extends de.uni_koblenz.jgralab.AttributedElement> getM1Class() {
		return de.uni_koblenz.oneoonecompanies.schema.Manager.class;
	}

	public Object getAttribute(String attributeName) {
		if (attributeName.equals("address")) return get_address();
		if (attributeName.equals("name")) return get_name();
		if (attributeName.equals("salary")) return get_salary();
		throw new NoSuchAttributeException("Manager doesn't contain an attribute " + attributeName);
	}

	public void setAttribute(String attributeName, Object data) {
		if (attributeName.equals("address")) {
			set_address((java.lang.String) data);
			return;
		}
		if (attributeName.equals("name")) {
			set_name((java.lang.String) data);
			return;
		}
		if (attributeName.equals("salary")) {
			set_salary((Integer) data);
			return;
		}
		throw new NoSuchAttributeException("Manager doesn't contain an attribute " + attributeName);
	}

	public java.lang.String get_address() {
		return _address;
	}

	public void set_address(java.lang.String _address) {
		this._address = _address;
		graphModified();
	}

	public java.lang.String get_name() {
		return _name;
	}

	public void set_name(java.lang.String _name) {
		this._name = _name;
		graphModified();
	}

	public int get_salary() {
		return _salary;
	}

	public void set_salary(int _salary) {
		this._salary = _salary;
		graphModified();
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
		_address = io.matchUtfString();
		set_address(_address);
		_name = io.matchUtfString();
		set_name(_name);
		_salary = io.matchInteger();
		set_salary(_salary);
	}

	public void readAttributeValueFromString(String attributeName, String value) throws GraphIOException {
		if (attributeName.equals("address")) {
			GraphIO io = GraphIO.createStringReader(value, getSchema());
			_address = io.matchUtfString();
			set_address(_address);
			return;
		}
		if (attributeName.equals("name")) {
			GraphIO io = GraphIO.createStringReader(value, getSchema());
			_name = io.matchUtfString();
			set_name(_name);
			return;
		}
		if (attributeName.equals("salary")) {
			GraphIO io = GraphIO.createStringReader(value, getSchema());
			_salary = io.matchInteger();
			set_salary(_salary);
			return;
		}
		throw new NoSuchAttributeException("Manager doesn't contain an attribute " + attributeName);
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
		io.space();
		io.writeUtfString(_address);
		io.writeUtfString(_name);
		io.writeInteger(_salary);
	}

	public String writeAttributeValueToString(String attributeName) throws IOException, GraphIOException {
		if (attributeName.equals("address")) {
			GraphIO io = GraphIO.createStringWriter(getSchema());
			io.writeUtfString(_address);
			return io.getStringWriterResult();
		}
		if (attributeName.equals("name")) {
			GraphIO io = GraphIO.createStringWriter(getSchema());
			io.writeUtfString(_name);
			return io.getStringWriterResult();
		}
		if (attributeName.equals("salary")) {
			GraphIO io = GraphIO.createStringWriter(getSchema());
			io.writeInteger(_salary);
			return io.getStringWriterResult();
		}
		throw new NoSuchAttributeException("Manager doesn't contain an attribute " + attributeName);
	}

	/* add all valid from edges */
	private static Set<java.lang.Class<? extends Edge>> validFromEdges = new HashSet<java.lang.Class<? extends Edge>>();
	
	/* (non-Javadoc)
	 * @see jgralab.Vertex:isValidAlpha()
	 */
	@Override
	public boolean isValidAlpha(Edge edge) {
		return validFromEdges.contains(edge.getM1Class());
	}
	
	{

		validFromEdges.add(de.uni_koblenz.oneoonecompanies.schema.Mentors.class);

	}
	
	/* add all valid to edges */
	private static Set<java.lang.Class<? extends Edge>> validToEdges = new HashSet<java.lang.Class<? extends Edge>>();
	
	/* (non-Javadoc)
	 * @see jgralab.Vertex:isValidOemga()
	 */
	@Override
	public boolean isValidOmega(Edge edge) {
		return validToEdges.contains(edge.getM1Class());
	}
	
	{

		validToEdges.add(de.uni_koblenz.oneoonecompanies.schema.HasEmployee.class);

	}

	@Override
	public de.uni_koblenz.oneoonecompanies.schema.Manager getNextManager() {
		return (de.uni_koblenz.oneoonecompanies.schema.Manager)getNextVertex(de.uni_koblenz.oneoonecompanies.schema.Manager.class);
	}

	@Override
	public de.uni_koblenz.oneoonecompanies.schema.NamedElement getNextNamedElement() {
		return (de.uni_koblenz.oneoonecompanies.schema.NamedElement)getNextVertex(de.uni_koblenz.oneoonecompanies.schema.NamedElement.class);
	}

	@Override
	public de.uni_koblenz.oneoonecompanies.schema.Person getNextPerson() {
		return (de.uni_koblenz.oneoonecompanies.schema.Person)getNextVertex(de.uni_koblenz.oneoonecompanies.schema.Person.class);
	}

	@Override
	public de.uni_koblenz.oneoonecompanies.schema.Mentors getFirstMentorsIncidence() {
		return (de.uni_koblenz.oneoonecompanies.schema.Mentors)getFirstIncidence(de.uni_koblenz.oneoonecompanies.schema.Mentors.class);
	}

	@Override
	public de.uni_koblenz.oneoonecompanies.schema.Mentors getFirstMentorsIncidence(EdgeDirection orientation) {
		return (de.uni_koblenz.oneoonecompanies.schema.Mentors)getFirstIncidence(de.uni_koblenz.oneoonecompanies.schema.Mentors.class, orientation);
	}

	@Override
	public de.uni_koblenz.oneoonecompanies.schema.HasEmployee getFirstHasEmployeeIncidence() {
		return (de.uni_koblenz.oneoonecompanies.schema.HasEmployee)getFirstIncidence(de.uni_koblenz.oneoonecompanies.schema.HasEmployee.class);
	}

	@Override
	public de.uni_koblenz.oneoonecompanies.schema.HasEmployee getFirstHasEmployeeIncidence(EdgeDirection orientation) {
		return (de.uni_koblenz.oneoonecompanies.schema.HasEmployee)getFirstIncidence(de.uni_koblenz.oneoonecompanies.schema.HasEmployee.class, orientation);
	}
		@Override
		public de.uni_koblenz.oneoonecompanies.schema.HasEmployee add_department(de.uni_koblenz.oneoonecompanies.schema.Department vertex) {
			return ((de.uni_koblenz.oneoonecompanies.schema.CompaniesGraph)getGraph()).createEdge(de.uni_koblenz.oneoonecompanies.schema.HasEmployee.class, (de.uni_koblenz.oneoonecompanies.schema.Department) vertex, (de.uni_koblenz.oneoonecompanies.schema.Manager) this);
		}
		@Override
		public java.util.List<? extends de.uni_koblenz.oneoonecompanies.schema.Department> remove_department() {
			java.util.List<de.uni_koblenz.oneoonecompanies.schema.Department> adjacences = new java.util.ArrayList<de.uni_koblenz.oneoonecompanies.schema.Department>();
			de.uni_koblenz.oneoonecompanies.schema.HasEmployee edge = (de.uni_koblenz.oneoonecompanies.schema.HasEmployee) getFirstIncidence(de.uni_koblenz.oneoonecompanies.schema.HasEmployee.class, EdgeDirection.IN);
			while (edge != null) {
				de.uni_koblenz.oneoonecompanies.schema.HasEmployee next = (de.uni_koblenz.oneoonecompanies.schema.HasEmployee) edge.getNextIncidence(de.uni_koblenz.oneoonecompanies.schema.HasEmployee.class, EdgeDirection.IN);
				adjacences.add((de.uni_koblenz.oneoonecompanies.schema.Department) edge.getThat());
				edge.delete();
				edge = next;
			}
			return adjacences;
		}
		@Override
		public boolean remove_department(de.uni_koblenz.oneoonecompanies.schema.Department vertex) {
			boolean elementRemoved = false;
			de.uni_koblenz.oneoonecompanies.schema.HasEmployee edge = (de.uni_koblenz.oneoonecompanies.schema.HasEmployee) getFirstIncidence(de.uni_koblenz.oneoonecompanies.schema.HasEmployee.class, EdgeDirection.IN);
			while (edge != null) {
				de.uni_koblenz.oneoonecompanies.schema.HasEmployee next = (de.uni_koblenz.oneoonecompanies.schema.HasEmployee) edge.getNextIncidence(de.uni_koblenz.oneoonecompanies.schema.HasEmployee.class, EdgeDirection.IN);
				if (edge.getThat().equals(vertex)) {			edge.delete();
					elementRemoved = true;
				}
				edge = next;
			}
			return elementRemoved;
		}
		@Override
		public de.uni_koblenz.oneoonecompanies.schema.Department get_department() {
			de.uni_koblenz.oneoonecompanies.schema.HasEmployee edge = (de.uni_koblenz.oneoonecompanies.schema.HasEmployee) getFirstIncidence(de.uni_koblenz.oneoonecompanies.schema.HasEmployee.class, EdgeDirection.IN);
			if (edge != null) {
				return (de.uni_koblenz.oneoonecompanies.schema.Department) edge.getThat();
			}
			return null;
		}
		@Override
		public de.uni_koblenz.oneoonecompanies.schema.Mentors add_mentee(de.uni_koblenz.oneoonecompanies.schema.Employee vertex) {
			return ((de.uni_koblenz.oneoonecompanies.schema.CompaniesGraph)getGraph()).createEdge(de.uni_koblenz.oneoonecompanies.schema.Mentors.class, (de.uni_koblenz.oneoonecompanies.schema.Manager) this, (de.uni_koblenz.oneoonecompanies.schema.Employee) vertex);
		}
		@Override
		public java.util.List<? extends de.uni_koblenz.oneoonecompanies.schema.Employee> remove_mentee() {
			java.util.List<de.uni_koblenz.oneoonecompanies.schema.Employee> adjacences = new java.util.ArrayList<de.uni_koblenz.oneoonecompanies.schema.Employee>();
			de.uni_koblenz.oneoonecompanies.schema.Mentors edge = (de.uni_koblenz.oneoonecompanies.schema.Mentors) getFirstIncidence(de.uni_koblenz.oneoonecompanies.schema.Mentors.class, EdgeDirection.OUT);
			while (edge != null) {
				de.uni_koblenz.oneoonecompanies.schema.Mentors next = (de.uni_koblenz.oneoonecompanies.schema.Mentors) edge.getNextIncidence(de.uni_koblenz.oneoonecompanies.schema.Mentors.class, EdgeDirection.OUT);
				adjacences.add((de.uni_koblenz.oneoonecompanies.schema.Employee) edge.getThat());
				edge.delete();
				edge = next;
			}
			return adjacences;
		}
		@Override
		public boolean remove_mentee(de.uni_koblenz.oneoonecompanies.schema.Employee vertex) {
			boolean elementRemoved = false;
			de.uni_koblenz.oneoonecompanies.schema.Mentors edge = (de.uni_koblenz.oneoonecompanies.schema.Mentors) getFirstIncidence(de.uni_koblenz.oneoonecompanies.schema.Mentors.class, EdgeDirection.OUT);
			while (edge != null) {
				de.uni_koblenz.oneoonecompanies.schema.Mentors next = (de.uni_koblenz.oneoonecompanies.schema.Mentors) edge.getNextIncidence(de.uni_koblenz.oneoonecompanies.schema.Mentors.class, EdgeDirection.OUT);
				if (edge.getThat().equals(vertex)) {			edge.delete();
					elementRemoved = true;
				}
				edge = next;
			}
			return elementRemoved;
		}
		@Override
		public de.uni_koblenz.oneoonecompanies.schema.Employee get_mentee() {
			de.uni_koblenz.oneoonecompanies.schema.Mentors edge = (de.uni_koblenz.oneoonecompanies.schema.Mentors) getFirstIncidence(de.uni_koblenz.oneoonecompanies.schema.Mentors.class, EdgeDirection.OUT);
			if (edge != null) {
				return (de.uni_koblenz.oneoonecompanies.schema.Employee) edge.getThat();
			}
			return null;
		}

	@Override
	public Iterable<de.uni_koblenz.oneoonecompanies.schema.Mentors> getMentorsIncidences() {
		return new IncidenceIterable<de.uni_koblenz.oneoonecompanies.schema.Mentors>(this, de.uni_koblenz.oneoonecompanies.schema.Mentors.class);
	}
	
	
	@Override
	public Iterable<de.uni_koblenz.oneoonecompanies.schema.Mentors> getMentorsIncidences(EdgeDirection direction) {
		return new IncidenceIterable<de.uni_koblenz.oneoonecompanies.schema.Mentors>(this, de.uni_koblenz.oneoonecompanies.schema.Mentors.class, direction);
	}

	@Override
	public Iterable<de.uni_koblenz.oneoonecompanies.schema.HasEmployee> getHasEmployeeIncidences() {
		return new IncidenceIterable<de.uni_koblenz.oneoonecompanies.schema.HasEmployee>(this, de.uni_koblenz.oneoonecompanies.schema.HasEmployee.class);
	}
	
	
	@Override
	public Iterable<de.uni_koblenz.oneoonecompanies.schema.HasEmployee> getHasEmployeeIncidences(EdgeDirection direction) {
		return new IncidenceIterable<de.uni_koblenz.oneoonecompanies.schema.HasEmployee>(this, de.uni_koblenz.oneoonecompanies.schema.HasEmployee.class, direction);
	}

	private static java.util.Map<String, DirectedM1EdgeClass> roleMap;

	static {
	roleMap = new java.util.HashMap<String, DirectedM1EdgeClass>();

	roleMap.put("mentee", new DirectedM1EdgeClass(de.uni_koblenz.oneoonecompanies.schema.Mentors.class, de.uni_koblenz.jgralab.EdgeDirection.OUT));

	roleMap.put("department", new DirectedM1EdgeClass(de.uni_koblenz.oneoonecompanies.schema.HasEmployee.class, de.uni_koblenz.jgralab.EdgeDirection.IN));

	}

	public DirectedM1EdgeClass getEdgeForRolename(String rolename) {
		return roleMap.get(rolename);
	}
}
